# Generated by Django 5.1.1 on 2024-09-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Joke',
            fields=[
                ('joke_text', models.TextField()),
                ('number', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
