# Generated by Django 5.1.1 on 2024-09-25 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joke',
            old_name='number',
            new_name='id',
        ),
    ]
